### ISSUE TITLE
xpeviewer_win32_portable_0.01.zip detected as virus on Windows 10

### ISSUE THREAD

**Issue by julianxhokaxhiu** [horsicq/XPEViewer#4]
Hi,

Just wanted to let you know that [`xpeviewer_win32_portable_0.01.zip` ](https://github.com/horsicq/XPEViewer/releases/download/0.01/xpeviewer_win32_portable_0.01.zip) is currently detected as `Trojan:Win32/Wacatac.C!ml` on Windows 10.

Is that on purpose? I wonder what does it contain that triggers Windows Defender so bad.

Thank you in advance for any feedback in case :) As well as thank you for all the awesome tools you've published. This is a gold mine for sure!

Cheers,
Julian

**Comment by horsicq** [comment]
Hello! Thanks a lot for the bugreport. The problem will be fixed in the next version.

If you need the version 0.01 without Windows Defender issues: https://github.com/horsicq/XPEViewer/releases/download/0.01/xpeviewer_win32_portable_noloader.zip

More information: https://github.com/horsicq/DIE-engine/issues/17

**Comment by julianxhokaxhiu** [comment]
Tested and works like a charm! Thank you :D
